### ISSUE TITLE
[BUG] Update dependencies in BUILD.md building instructions

### ISSUE THREAD

**Issue by gabrielepmattia** [eclipse-fog05/fog05#170] opened 2020-01-27 10:12 UTC
**Describe the bug**
Hitting `make`, after following BUILD.md instructions, returns

```
make -C sdk/sdk-ocaml install
make[1]: Entering directory '/home/debian/Downloads/fog05/sdk/sdk-ocaml'
opam install . --working-dir
[fos-sdk.0.1] synchronised from git+file:///home/debian/Downloads/fog05/sdk/sdk-ocaml#HEAD
The following dependencies couldn't be met:
  - fos-sdk → yaks-common >= 0.3.0
      no matching version

No solution found, exiting
make[1]: *** [Makefile:71: install] Error 20
make[1]: Leaving directory '/home/debian/Downloads/fog05/sdk/sdk-ocaml'
make: *** [Makefile:23: ocaml-sdk] Error 2
```

**To Reproduce**
1. Follow the building script
2. `make submodules`
3. `make`

**Expected behavior**
No error should be reported

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian
 - Version: 10
 - Involved plugin: None

**Additional context**
None

**Comment by ilmoro90** [comment] 2020-01-27 11:39
i'm in the same trouble, but my error has a little difference:
<pre>make -C sdk/sdk-ocaml install
make[1]: ingresso nella directory &quot;/fog05/sdk/sdk-ocaml&quot;
opam install . --working-dir
<font color="#C4A000">[WARNING]</font> Running as root is not recommended
[<font color="#4E9A06">fos-sdk.0.1</font>] no changes from git+file:///fog05/sdk/sdk-ocaml#HEAD
The following dependencies couldn&apos;t be met:
  - fos-sdk<font color="#C4A000"> → </font><font color="#EF2929"><b>yaks-common</b></font>
      unknown package

No solution found, exiting
make[1]: *** [Makefile:71: install] Error 20
make[1]: uscita dalla directory &quot;/fog05/sdk/sdk-ocaml&quot;
make: *** [Makefile:23: ocaml-sdk] Error 2
</pre>

**Comment by gabrik** [comment] 2020-01-27 13:14
Hi both, this comes from an actual mistake done on Friday.
#169 is supposed to fix this.
In any case please do not use the `make submodules` but just the git command `git submodule update --init --recursive`

There are ongoing PR in both sdk-ocaml and api-ocaml to tackle the dependency versioning.

**Comment by ilmoro90** [comment] 2020-01-27 17:10
i have already tried,  as suggested [here](https://gitter.im/atolab/fog05) but it did not work

**Comment by gabrik** [comment] 2020-01-31 14:58
Hi all, PR #173 and #172 should have fixed this.

**Comment by gabrielepmattia** [comment] 2020-01-31 16:50
Thank you @gabrik

Please @ilmoro90 retry to build from scratch, since from auto-build I get dependencies errors #175

**Comment by ilmoro90** [comment] 2020-01-31 17:17
yes i'm trying to do that

**Comment by ilmoro90** [comment] 2020-02-01 10:37
i tried to rebuild from scratch, now i have some trouble with enable.sh. 
i execute it and get no errors, then if i try `sudo systemctl status yaks` i got failure. moreover the command `yaksd -vv` produce: command not found. 
where i'm get wrong?

**Comment by gabrielepmattia** [comment] 2020-02-03 09:16
> i tried to rebuild from scratch, now i have some trouble with enable.sh.
> i execute it and get no errors, then if i try `sudo systemctl status yaks` i got failure. moreover the command `yaksd -vv` produce: command not found.
> where i'm get wrong?

Are you sure that you get no errors when building fog05? I'm still getting dependencies errors:
```
[apero-core.0.4.6] synchronised from git+file:///home/debian/fog05/fos_build/apero-core#HEAD
[dynload-sys.0.4.6] synchronised from git+file:///home/debian/fog05/fos_build/apero-core#HEAD
The following actions will be performed:
  ∗ install apero-core  0.4.6*
  ∗ install dynload-sys 0.4.6*
===== ∗ 2 =====

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
∗ installed apero-core.0.4.6
[ERROR] The compilation of dynload-sys failed at "/home/debian/.opam/opam-init/hooks/sandbox.sh build dune build --only dynload-sys --root . -j 1
        @install".

#=== ERROR while compiling dynload-sys.0.4.6 ==================================#
# context     2.0.6 | linux/x86_64 | ocaml-base-compiler.4.09.0 | pinned(git+file:///home/debian/fog05/fos_build/apero-core#HEAD#559ba547)
# path        ~/.opam/default/.opam-switch/build/dynload-sys.0.4.6
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build --only dynload-sys --root . -j 1 @install
# exit-code   1
# env-file    ~/.opam/log/dynload-sys-25423-c743ac.env
# output-file ~/.opam/log/dynload-sys-25423-c743ac.out
### output ###
# File "lib/dune", line 14, characters 19-29:
# 14 |   (libraries       apero-core))
#                         ^^^^^^^^^^
# Error: Library "apero-core" not found.
# Hint: try: dune external-lib-deps --missing --root . --only dynload-sys -j 1
#   @install
```
Again seems that `dynload-sys` needs `apero-core` to be installed but it gets installed before it. Same confirmed in the [travis autobuild](https://travis-ci.org/gabrielepmattia/fog05/jobs/645356351#L1641)

**Comment by gabrielepmattia** [comment] 2020-02-03 09:28
@gabrik I notice that in [BUILD.md](https://github.com/eclipse-fog05/fog05/blob/eacf26b015c88c199e47d2ec60c5227c1d93be14/BUILD.md) we install packages with the command `opam install . --working-dir -y` but for example in the [`apero-core`](https://github.com/atolab/apero-core) Makefile there is an install rule which runs `dune install` and it seems to generate no errors. Which command is the right one? Because `opam install` checks dependencies order and causes the error mentioned above, while `dune` seems not to do it.

**Comment by ilmoro90** [comment] 2020-02-03 10:20
by executing these command:
```
$ cd fog05
$ git submodule update --init --recursive
$ make
```
i obtained:
```
make -C sdk/sdk-ocaml install
make[1]: ingresso nella directory "/home/daniele/Documenti/fog05/sdk/sdk-ocaml"
opam install . --working-dir
[fos-sdk.0.1] synchronised from git+file:///home/daniele/Documenti/fog05/sdk/sdk-ocaml#HEAD
The following actions will be performed:
  ↻ recompile fos-sdk     0.1*
  ↻ recompile fos-fim-api 0.1* [uses fos-sdk]
===== ↻ 2 =====
Do you want to continue? [Y/n] y

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⊘ removed   fos-fim-api.0.1
⊘ removed   fos-sdk.0.1
∗ installed fos-sdk.0.1
∗ installed fos-fim-api.0.1
Done.
make[1]: uscita dalla directory "/home/daniele/Documenti/fog05/sdk/sdk-ocaml"
make -C api/api-ocaml install
make[1]: ingresso nella directory "/home/daniele/Documenti/fog05/api/api-ocaml"
opam pin fos-fim-api .
[NOTE] Package fos-fim-api is already pinned to git+file:///home/daniele/Documenti/fog05/api/api-ocaml#HEAD (version 0.1).
[fos-fim-api.0.1] no changes from git+file:///home/daniele/Documenti/fog05/api/api-ocaml#HEAD
fos-fim-api is now pinned to git+file:///home/daniele/Documenti/fog05/api/api-ocaml#HEAD (version 0.1)

Already up-to-date.
Nothing to do.
make[1]: uscita dalla directory "/home/daniele/Documenti/fog05/api/api-ocaml"
make -C src/agent
make[1]: ingresso nella directory "/home/daniele/Documenti/fog05/src/agent"
dune build
make[1]: uscita dalla directory "/home/daniele/Documenti/fog05/src/agent"
```

i got the installation on saturday, for this reason "nothing up-to-date". It seems gone ok, but i still have `yaks -vv` problem

**Comment by gabrik** [comment] 2020-02-03 11:54
Hi both
Let me answer your issues.

@gabrielepmattia 
The dependency error that you got for `dynload-sys` comes by a change of 90% from `dune` using dune 1.11.4 should avoid this strange dependency issue.

Regarding the differences between `dune install` and `opam install`, dune is the build system, while opam is the dependency system. Installing using dune does not verify the dependencies, this is why in the [BUILD.md](https://github.com/eclipse-fog05/fog05/blob/eacf26b015c88c199e47d2ec60c5227c1d93be14/BUILD.md) we use opam instead of dune.

@ilmoro90 

In the latest commits, the `yaks` command was replaced by `/etc/fos/zenohd -P "/etc/fos/yaks-plugin.cmxs -s /**"` 
Please verify if your service file is using the right command. Otherwise, I suggest removing fog05 and reinstall it.

**Comment by ilmoro90** [comment] 2020-02-03 12:12
ok, so there is an error [here](https://github.com/eclipse-fog05/fog05/blob/master/INSTALL.md) where you suggest to starts yaks server by yaksd -vv? 
how to check if my service file is using the right command?

**Comment by gabrik** [comment] 2020-02-03 12:56
Indeed the INSTALL.md needs to be updated

**Comment by ilmoro90** [comment] 2020-02-04 09:07
> how to check if my service file is using the right command?
@gabrik

**Comment by gabrik** [comment] 2020-02-04 09:47
Sorry @ilmoro90 

Just verify using cat
```
$ cat /lib/systemd/system/yaks.service
[unit]
Description = YAKS Daemon
After=network.target


[Service]
Type=simple
PIDFile=/var/fos/yaksd.pid
ExecStart = /etc/fos/zenohd -P "/etc/fos/yaks-plugin.cmxs -s /**"
KillMode=process
Restart=on-failure
[Install]
WantedBy=multi-user.target
Alias=yaks.service
```

**Comment by ilmoro90** [comment] 2020-02-04 09:58
ok i have the same output...how to start fog05 now?

**Comment by gabrik** [comment] 2020-02-04 10:02
Try by using the services.

```
$ sudo systemctl start yaks
$ sudo systemctl start fos_agent
$ sudo systemctl start fos_linux
$ sudo systemctl start fos_linuxbridge #if installed
$ sudo systemctl start fos_lxd #if installed
```
You can verify the status using `journalctl`, like `journalctl -u fos_agent` or if you want to follow the log `journalctl -u fos_agent -f`

You can replace `fos_agent` with one of the other services

**Comment by ilmoro90** [comment] 2020-02-04 10:58
got a problem with zenohd, i will try to find error in building

**Comment by gabrik** [comment] 2020-02-04 15:51
Can you please paste the error?

**Comment by ilmoro90** [comment] 2020-02-04 17:58
by executing command:
`sudo journalctl -u yaks`
i get:
```
...
systemd[32279]: yaks.service: Failed to execute command: No such file or directory
systemd[32279]: yaks.service: Failed at step EXEC spawning /etc/fos/zenohd: No such file or directory
...
```

but i installed zenohd..

**Comment by gabrik** [comment] 2020-02-05 07:44
Can you paste the output of `ls -al /etc/fos` ?

**Comment by ilmoro90** [comment] 2020-02-06 10:34
ok zenoh doesn't appear, but i installed without error...i will try to do it again.
```
totale 28132
drwxr-xr-x   4 root    root        4096 gen 31 20:53 .
drwxr-xr-x 123 root    root       12288 feb  6 11:31 ..
-rwxr-xr-x   1 root    root    28776888 gen 31 20:53 agent
-rw-r--r--   1 root    root         464 gen 31 20:53 agent.json
drwxr-xr-x   5 root    root        4096 feb  1 10:43 plugins
drwxrwxr-x   2 daniele daniele     4096 gen 27 09:29 yaks
```

**Comment by gabrielepmattia** [comment] 2020-02-06 11:04
Hi @ilmoro90 try to clean your environment re-clone the repository, then follow the up-to-date [BUILD.md](https://github.com/eclipse-fog05/fog05/blob/master/BUILD.md) file, then keep us updated

**Comment by ilmoro90** [comment] 2020-02-06 19:12
ok i tried to execute code until:
`./build.sh`

in build.md you have to remove:
```
$ cd fog05
$ git submodule update --init --recursive
$ make
```
because is inside build.sh

then i installed the plugin, i changed the machine id of the 2 plugin, i executed enable.sh and start.sh.

Then? if 
```
yaksd -vv
```
doesn't work how i have to proceed?

**Comment by gabrik** [comment] 2020-02-07 08:19
> Then? if
> 
> ```
> yaksd -vv
> ```
> 
> doesn't work how i have to proceed?

It is `zenohd` file present into `/etc/fos` ?

**Comment by ilmoro90** [comment] 2020-02-07 09:19
`ls -al /etc/fos`
produces same output as before:
```
totale 29068
drwxr-xr-x   4 root root     4096 feb  6 19:40 .
drwxr-xr-x 122 root root    12288 feb  7 10:16 ..
-rwxr-xr-x   1 root root 29736480 feb  6 19:40 agent
-rw-r--r--   1 root root      464 feb  6 19:40 agent.json
drwxr-xr-x   5 root root     4096 feb  6 19:48 plugins
drwxrwxr-x   2 moro moro     4096 gen 27 09:29 yaks
```

**Comment by gabrik** [comment] 2020-02-07 10:31
I see, that YAKS is an old version, you are supposed to get something similar.

```
$ ls -al /etc/fos/
total 60384
drwxr-xr-x   5 ato  ato       4096 janv. 22 14:20 .
drwxr-xr-x 152 root root     12288 févr.  5 10:39 ..
-rwxr-xr-x   1 root root  29644760 janv. 30 14:38 agent
-rw-r--r--   1 root root       464 janv. 22 14:19 agent.json
drwxrwxr-x   3 ato  ato       4096 janv. 30 17:37 containerd
drwxr-xr-x   8 ato  ato       4096 janv. 30 10:35 plugins
drwxr-xr-x   3 ato  ato       4096 mai   28  2019 rest
-rwxr-xr-x   1  501 staff   447272 janv. 30 10:35 yaks-plugin.cmxs
-rwxr-xr-x   1  501 staff       71 sept. 24 19:29 yaksd
-rwxr-xr-x   1  501 staff 31695912 janv. 30 10:36 zenohd
```


In this case, you can fix this using the same commands used in the Makefile.

```
$ curl -L -o /tmp/yaks.tar.gz https://www.dropbox.com/s/hx6w8qs9i4cx5r1/yaks.0.3.0.tar.gz
$ tar -xzvf /tmp/yaks.tar.gz -C /etc/fos
$ rm -rf /tmp/yaks.tar.gz
```
and then start it using `/etc/fos/zenohd -P "/etc/fos/yaks-plugin.cmxs -s /**"`

**Comment by ilmoro90** [comment] 2020-02-07 11:11
`tar -xzvf /tmp/yaks.tar.gz -C /etc/fos`

produces
```
yaks/
yaks/zenohd
yaks/yaks-plugin.cmxs
```
and
`ls -al /etc/fos/`
produces same bad result as before

it is normal that zenohd is inside yaks?

**Comment by gabrik** [comment] 2020-02-07 11:15
Got it, It is not supposed to be inside the yaks directory but directly under `/etc/fos`
I'm going to fix this in #176 
The plan is to not have it to be downloaded for dropbox, but instead build it during the dependencies building.

**Comment by ilmoro90** [comment] 2020-02-07 11:16
ok, so i ca try to move zenohd directory inside fos and try to enable and start?

**Comment by gabrik** [comment] 2020-02-07 11:24
Yes you can try this trick

**Comment by ilmoro90** [comment] 2020-02-07 11:34
no problem executing  `enable` and `start` but then? 
i tried:

```
python3
>>> from fog05 import FIMAPI
>>> api = FIMAPI(locator='127.0.0.1') # or locator='IP of the YAKS server'
```

but got an error
```
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fog05 import FIMAPI
>>> api = FIMAPI(locator='127.0.0.1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/fog05-0.1.0-py3.7.egg/fog05/fimapi.py", line 55, in __init__
  File "/usr/local/lib/python3.7/dist-packages/fog05_sdk-0.1.0-py3.7.egg/fog05_sdk/yaks_connector.py", line 2317, in __init__
  File "/usr/local/lib/python3.7/dist-packages/yaks-0.3.0-py3.7.egg/yaks/yaks.py", line 54, in login
    return Yaks(Zenoh.open(locator, zprops))
  File "/usr/local/lib/python3.7/dist-packages/zenoh-0.3.0-py3.7.egg/zenoh/zenoh_api.py", line 236, in open
    return Zenoh(locator, properties)
  File "/usr/local/lib/python3.7/dist-packages/zenoh-0.3.0-py3.7.egg/zenoh/zenoh_api.py", line 129, in __init__
    Zenoh.zenoh_native_lib = CDLL(zenoh_lib_path)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/libzenohc.so: cannot open shared object file: No such file or directory
```

**Comment by gabrik** [comment] 2020-02-07 11:42
That's odd. You are missing the dependency `zenoh-c`

It is installed in the `build.sh`, strangely, you do not find it.
You can install it by hand using these commands:

```
git clone http://github.com/atolab/zenoh-c
cd zenoh-c
git checkout 0.3.0
make
make install
```
Then verify if it is present by running `file /usr/local/lib/libzenohc.so`

Please let us know for any other issue.
And then ver

**Comment by ilmoro90** [comment] 2020-02-07 12:03
ok, now i got no errors, but:
```
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fog05 import FIMAPI
>>> api = FIMAPI(locator='127.0.0.1')
>>> api.node.list()
[]
>>> 

```

**Comment by gabrik** [comment] 2020-02-07 13:31
You can verify the actual status of the services using `systemctl status <name of the service>` and the log using `journalctl -u <name of the service> -f`

Can you please verify if `fos_agent` and `fos_linux` are reporting any error?

**Comment by ilmoro90** [comment] 2020-02-07 13:45
```
● fos_linux.service
   Loaded: loaded (/lib/systemd/system/fos_linux.service; enabled; vendor preset
   Active: failed (Result: exit-code) since Fri 2020-02-07 13:05:09 CET; 1h 39mi
  Process: 3658 ExecStart=/etc/fos/plugins/plugin-os-linux/linux_plugin /etc/fos
 Main PID: 3658 (code=exited, status=1/FAILURE)
```

**Comment by gabrik** [comment] 2020-02-07 13:53
Ok, can you please paste the output of this service? `journalctl -u fos_linux -f` ?

**Comment by ilmoro90** [comment] 2020-02-07 14:01
i used `sudo journalctl -u fos_linux -f`: 
```
-- Logs begin at Fri 2020-02-07 10:16:16 CET. --
feb 07 13:05:09 debian fos_linux[3658]:   File "/usr/local/lib/python3.7/dist-packages/fog05_sdk-0.1.0-py3.7.egg/fog05_sdk/yaks_connector.py", line 1714, in get_node_configuration
feb 07 13:05:09 debian fos_linux[3658]: ValueError: Empty data on get_node_configuration
feb 07 13:05:09 debian systemd[1]: fos_linux.service: Main process exited, code=exited, status=1/FAILURE
feb 07 13:05:09 debian systemd[1]: fos_linux.service: Failed with result 'exit-code'.
feb 07 13:05:09 debian systemd[1]: fos_linux.service: Service RestartSec=100ms expired, scheduling restart.
feb 07 13:05:09 debian systemd[1]: fos_linux.service: Scheduled restart job, restart counter is at 5.
feb 07 13:05:09 debian systemd[1]: Stopped fos_linux.service.
feb 07 13:05:09 debian systemd[1]: fos_linux.service: Start request repeated too quickly.
feb 07 13:05:09 debian systemd[1]: fos_linux.service: Failed with result 'exit-code'.
feb 07 13:05:09 debian systemd[1]: Failed to start fos_linux.service.
```

**Comment by gabrik** [comment] 2020-02-07 14:04
It complains about not being able to get the node configuration.
Can you please paste the output of `cat /etc/machine-id` and `cat /etc/fos/plugins/plugin-os-linux/linux_plugin.json` ?

**Comment by ilmoro90** [comment] 2020-02-07 14:11
`5926ee77fad940f2bb8e76034953fdd8`
and
```
.json
{
  "name": "linux",
  "version": 1,
  "uuid": "49c652d1-f8bc-4220-ae20-53526e4fef09",
  "type": "os",
  "description": "linux os plugin",
  "configuration": {
    "ylocator": "tcp/127.0.0.1:7447",
    "nodeid": "5926ee77-fad9-40f2-bb8e-76034953fdd8",
    "expose": true,
    "update_interval": 5
  }
}
```
my bad? i have to substitute both id?

**Comment by gabrik** [comment] 2020-02-07 14:18
No, the id seems correct.
I'm wondering if is the agent that hangs and does not write the configuration.
Can you paste the output of `sudo journalctl -u fos_agent -f` ?

**Comment by ilmoro90** [comment] 2020-02-07 14:19
```
-- Logs begin at Fri 2020-02-07 10:16:16 CET. --
feb 07 12:20:15 debian fos_agent[2681]: agent: [DEBUG] Reading AckNack
feb 07 12:20:15 debian fos_agent[2681]: agent: [DEBUG]
feb 07 12:20:15 debian fos_agent[2681]: [received: AckNack]
feb 07 12:20:15 debian fos_agent[2681]: >>
feb 07 12:20:15 debian fos_agent[2681]: [FOSAGENT] Up & Running!
feb 07 13:05:00 debian systemd[1]: /lib/systemd/system/fos_agent.service:1: Unknown section 'unit'. Ignoring.
feb 07 13:05:00 debian systemd[1]: /lib/systemd/system/fos_agent.service:1: Unknown section 'unit'. Ignoring.
feb 07 13:05:00 debian systemd[1]: /lib/systemd/system/fos_agent.service:1: Unknown section 'unit'. Ignoring.
feb 07 13:05:00 debian systemd[1]: /lib/systemd/system/fos_agent.service:1: Unknown section 'unit'. Ignoring.
feb 07 13:05:00 debian systemd[1]: /lib/systemd/system/fos_agent.service:1: Unknown section 'unit'. Ignoring.
```

**Comment by gabrik** [comment] 2020-02-07 14:33
That's odd.

If you run this python code you get something?

```
from yaks import Yaks
y = Yaks.login('')
ws = y.workspace('/')
res = ws.get('/alfos/5926ee77-fad9-40f2-bb8e-76034953fdd8/configuration')
print('{}'.format(res))
```

**Comment by ilmoro90** [comment] 2020-02-07 14:37
`$from yaks import Yaks`

generates 

```
from: can't read /var/mail/yaks
```

**Comment by gabrik** [comment] 2020-02-07 14:47
That code is python, my bad I did not explain it. So you gave to run it inside a `python3`

**Comment by ilmoro90** [comment] 2020-02-07 14:50
```
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from yaks import Yaks
>>> y = Yaks.login('')
>>> ws = y.workspace('/')
>>> res = ws.get('/alfos/5926ee77-fad9-40f2-bb8e-76034953fdd8/configuration')
>>> print('{}'.format(res))
[]
>>> 
```

**Comment by gabrik** [comment] 2020-02-07 14:53
If you replace `res = ws.get('/alfos/5926ee77-fad9-40f2-bb8e-76034953fdd8/configuration')` with `res = ws.get('/alfos/**)` same empty array?

**Comment by ilmoro90** [comment] 2020-02-07 15:11
```
>>> res = ws.get('/alfos/**)
  File "<stdin>", line 1
    res = ws.get('/alfos/**)
                           ^
SyntaxError: EOL while scanning string literal
```

**Comment by gabrik** [comment] 2020-02-07 15:13
Sorry, my bad I forgot to close the string `res = ws.get('/alfos/**')`

**Comment by ilmoro90** [comment] 2020-02-07 15:14
same null array

**Comment by gabrik** [comment] 2020-02-07 15:19
Ok, I have just merged #176, and tested on a clean Debian installation and it is working.
Can you try to update to this last version?

Should suffice to:
```
$ git pull
$ sudo rm -rf /var/fos /etc/fos /usr/local/lib/libzenohc.so  /usr/local/include/zenoh
$ sudo pip3 uninstall fog05 fog05_sdk zenoh yaks -y 
$ opam remove apero-core
$ ./build.sh
$ sudo make install
```

**Comment by ilmoro90** [comment] 2020-02-07 15:26
again empty

**Comment by gabrik** [comment] 2020-02-07 15:40
Ok, which exact version of Debian are you running? And which kernel?
You can check with `cat /etc/os-release` and `uname -a`
I'm going to reproduce as much as possible

**Comment by ilmoro90** [comment] 2020-02-07 15:42
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
```
Linux debian 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
```

**Comment by gabrik** [comment] 2020-02-07 18:14
Just done some testing in the same distribution and it is working.
```
ato@debian:/etc/fos$ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fog05 import API
>>> from fog05 import FIMAPI
>>> a = FIMAPI('')
>>> a.node.list()
['56ef8629-80d8-4a91-a8e3-fe9cfbf79d4c']
>>>
```

We can verify the sha256sum of the binaries to check if there is something wrong with your installation.
```
$ sha256sum /etc/fos/agent
70f1e4fa525283d72dd1d6bbfab6b2a75f28be3347e6749b70544bbdf0f88bde  /etc/fos/agent
$ sha256sum /etc/fos/zenohd
187cc30cde775c0a00d2837c456bdeca4ae041fd2530fe2c1761f1c8aecc7290  /etc/fos/zenohd
$ sha256sum /etc/fos/yaks-plugin.cmxs
32e0219656c7b4fa7a8f3496e835386214deb36afac513c78a1606288c5f02c9  /etc/fos/yaks-plugin.cmxs
```

If they are different from the yours I guess there is something wrong in your installation

**Comment by ilmoro90** [comment] 2020-02-07 18:27
```
$ sha256sum /etc/fos/agent
7da405a9c15b7d76c7ec549432ff054702f6517ac4e19d07631eb9d0a5af9b95  /etc/fos/agent
$ sha256sum /etc/fos/zenohd
7ce6234fe81996bbc64a0c731828a367eef571bb384abe108fcc85279342ca76  /etc/fos/zenohd
$ sha256sum /etc/fos/yaks-plugin.cmxs
968d2e2ddca124f50cd8308bc77661d454123171f499e6dcfdd25c4c11ba12c7  /etc/fos/yaks-plugin.cmxs
```
ok are different...now, the directory of building and installation, make difference?

**Comment by gabrik** [comment] 2020-02-10 16:52
That's should not pose any difference in the binaries.

Can you paste the output of `opam list | grep apero`, `opam list | grep zenoh` and 'opam list | grep yaks` ?

**Comment by ilmoro90** [comment] 2020-02-10 16:54
i solved, now i have the id inside the list. i reinstalled changing directory now it works.
all pinned to: 0.4.6 / 0.3.0 / 0.3.0

**Comment by gabrik** [comment] 2020-02-10 17:01
I'll close this, please open a new one if you have any other issue.

**Closed by gabrik** 2020-02-10 17:01 UTC
Labels: bug
