### ISSUE TITLE
[ERROR] The installation of z_storage failed at "dune build -p z_storage

### ISSUE THREAD

**Issue by ilmoro90** [eclipse-fog05/fog05#168] opened 2020-01-24 11:20 UTC
When i try to install zenoh i get an error:

<pre><font color="#CC0000">[ERROR]</font> The installation of z_storage failed at &quot;dune build -p z_storage
        @install&quot;.
</pre>

and:

<pre><font color="#CC0000">#===</font> <b>ERROR</b> <b>while installing z_storage.0.2.5</b> <font color="#CC0000">===================================#</font>
<font color="#C4A000">#</font> <font color="#C4A000">context</font>     2.0.6 | linux/x86_64 | ocaml-base-compiler.4.07.1 | pinned(git+file:///root/fos_build/zenoh#HEAD#46d43788)
<font color="#C4A000">#</font> <font color="#C4A000">path</font>        ~/.opam/fos/.opam-switch/build/z_storage.0.2.5
<font color="#C4A000">#</font> <font color="#C4A000">command</font>     ~/.opam/opam-init/hooks/sandbox.sh install dune build -p z_storage @install
<font color="#C4A000">#</font> <font color="#C4A000">exit-code</font>   1
<font color="#C4A000">#</font> <font color="#C4A000">env-file</font>    ~/.opam/log/z_storage-28741-f2076a.env
<font color="#C4A000">#</font> <font color="#C4A000">output-file</font> ~/.opam/log/z_storage-28741-f2076a.out
<font color="#C4A000">### output ###</font>
<font color="#C4A000"># </font>File &quot;example/plugins/dune&quot;, line 7, characters 19-30:
<font color="#C4A000"># </font>7 |   (libraries       zenoh-ocaml dynload-sys)
<font color="#C4A000"># </font>                       ^^^^^^^^^^^
<font color="#C4A000"># </font>Error: Library &quot;zenoh-ocaml&quot; not found.
<font color="#C4A000"># </font>Hint: try: dune external-lib-deps --missing -p z_storage @install

<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>Error report</b> <font color="#06989A">&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
<font color="#CC0000">┌─ </font>The following actions <font color="#CC0000">failed</font>
<font color="#CC0000">│ </font><font color="#4E9A06">∗</font> install <b>z_storage</b> 0.2.5
<font color="#CC0000">└─ </font>
</pre>

in your opinion i have to follow in the installation anyway o try with the hint?

<pre># Hint: try: dune external-lib-deps --missing -p z_storage @install</pre>

**Comment by gabrik** [comment] 2020-01-24 11:45
Hi, that's accually not an issue.
zenoh should be installed, you can check using `opam list | grep zenoh`

You should get something similar.


```
$ opam list | grep zenoh
zenoh                   0.2.5       pinned to version 0.2.5 at git+file:///home/ato/Workspace/eclipse/fos_build/zenoh#HEAD
zenoh-http              0.2.5       pinned to version 0.2.5 at git+file:///home/ato/Workspace/eclipse/fos_build/zenoh#HEAD
zenoh-ocaml             0.2.5       pinned to version 0.2.5 at git+file:///home/ato/Workspace/eclipse/fos_build/zenoh#HEAD
zenoh-proto             0.2.5       pinned to version 0.2.5 at git+file:///home/ato/Workspace/eclipse/fos_build/zenoh#HEAD
zenoh-router            0.2.5       pinned to version 0.2.5 at git+file:///home/ato/Workspace/eclipse/fos_build/zenoh#HEAD
zenoh-router-daemon     0.2.5       pinned to version 0.2.5 at git+file:///home/ato/Workspace/eclipse/fos_build/zenoh#HEAD
zenoh-router-lib        0.2.5       pinned to version 0.2.5 at git+file:///home/ato/Workspace/eclipse/fos_build/zenoh#HEAD
zenoh-tx-inet           0.2.5       pinned to version 0.2.5 at git+file:///home/ato/Workspace/eclipse/fos_build/zenoh#HEAD
```

**Comment by ilmoro90** [comment] 2020-01-24 12:04
i do not understand.  With command:

$ git clone https://github.com/atolab/zenoh
$ cd zenoh
$ git checkout 46d4378
$ opam install . --working-dir -y

am i installing zenoh?

**Comment by gabrik** [comment] 2020-01-24 13:07
Yes, that command installs Zenoh, usually it installs all the zenoh packages except the z_storage.
That one is an example package so even if it goes on error it is not a big deal.

**Comment by ilmoro90** [comment] 2020-01-24 15:34
ok but at the end zenoh was not installed. i'm trying again

**Comment by gabrik** [comment] 2020-01-24 15:35
Maybe the issue is coming also from another package.
Can you check the version of `dune`

Should be something like this, in any case it should be less that 2.0

```
$ dune --version
1.11.4
```

**Comment by ilmoro90** [comment] 2020-01-24 15:52
yeah it's correct

**Comment by ghisellinicola** [comment] 2020-01-24 17:13
I too am trying to compile the project manually but I am stuck in a similar point.

I started with a clean debian virtual machine.

Following the step-by-step instructions for manual compilation, I encountered this error:

`
=== ERROR while installing zenoh-proto.0.2.5 =================================#
 context     2.0.6 | linux/x86_64 | ocaml-base-compiler.4.07.1 | pinned(git+file:///home/fogos/fos_build/zenoh#HEAD#46d43788)
 path        ~/.opam/fos/.opam-switch/build/zenoh-proto.0.2.5
 command     ~/.opam/opam-init/hooks/sandbox.sh install dune build @install
 exit-code   1
 env-file    ~/.opam/log/zenoh-proto-16402-0ee25e.env
 output-file ~/.opam/log/zenoh-proto-16402-0ee25e.out
=================== output ===========================
 File "src/zenoh-proto/message.mli", line 2, characters 5-12:
 Error: Unbound module Locator
`

I tryed to add manually the missing dependencies by doing:

`
cp fos_build/apero-net/lib/*.m*  fos_build/zenoh/src/zenoh-proto/
`

It works, but immediately another error raises:

`
=== ERROR while installing zenoh-proto.0.2.5 =================================#
context     2.0.6 | linux/x86_64 | ocaml-base-compiler.4.07.1 | pinned(git+file:///home/fogos/fos_build/zenoh#HEAD#46d43788)
path        ~/.opam/fos/.opam-switch/build/zenoh-proto.0.2.5
command     ~/.opam/opam-init/hooks/sandbox.sh install dune build @install
exit-code   1
env-file    ~/.opam/log/zenoh-proto-24791-44ea43.env
output-file ~/.opam/log/zenoh-proto-24791-44ea43.out
=== output ===
File "src/zenoh-proto/netServiceWebSock.mli", line 29, characters 41-73:
Error: Unbound module Websocket_lwt
`

And I'm not able to figure out how to solve it. 

Actually I noticed that my version of dune is 2.1.3 and maybe this is the problem. 
How can I change it? This will solve the problem?

**Comment by gabrik** [comment] 2020-01-27 08:02
Hi @ghisellinicola,
Yes, I guess the dune version is the issue, you can downgrade that using opam. 
```
opam install dune.1.11.4
```
Then verify that the dependencies for zenoh (apero-core, dynload-sys, apero-net, apero-time) are installed 
```
opam list | grep apero
apero-core              0.4.5          pinned to version 0.4.5 at git+file:///Users/gabri/Workspace/apero-core#HEAD
apero-net               0.4.5          pinned to version 0.4.5 at git+file:///Users/gabri/Workspace/apero-net#HEAD
apero-time              0.4.5          pinned to version 0.4.5 at git+file:///Users/gabri/Workspace/apero-time#HEAD
dynload-sys             0.4.5          pinned to version 0.4.5 at git+file:///Users/gabri/Workspace/apero-core#HEAD
```

**Comment by gabrielepmattia** [comment] 2020-01-27 09:52
@gabrik @ilmoro90 It seems that `z_storage` gets installed before `zenoh-ocaml` package when executing `opam install . --working-dir`. This causes the error:

```
# File "example/plugins/dune", line 7, characters 19-30:
# 7 |   (libraries       zenoh-ocaml dynload-sys)
#                        ^^^^^^^^^^^
# Error: Library "zenoh-ocaml" not found.
# Hint: try: dune external-lib-deps --missing -p z_storage @install
```

 Indeed, by hitting again `opam install . --working-dir`, the `z_package` gets successful installed.

**Comment by ilmoro90** [comment] 2020-01-27 11:35
perfect i will try

**Comment by gabrik** [comment] 2020-01-27 12:51
Hi @ghisellinicola, @ilmoro90 
Indeed that package will be installed once `zenoh-ocaml` is there. But as said it is not essential. It is just an example package. 

Please bear in mind that once we have the first release (14th Feb) the version of some of the dependencies will change.

**Comment by ghisellinicola** [comment] 2020-01-29 10:42
@gabrik thank you vey much, downgrading dune worked.

**Closed** 2020-01-31 14:58 UTC
Labels: bug
